name: flutter_svg
description: An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
repository: https://github.com/flutter/packages/tree/main/third_party/packages/flutter_svg
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+flutter_svg%22
version: 2.3.0
publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  vector_graphics:
    git: https://github.com/kumsumit/vector_graphics.git
  vector_graphics_codec:
    git: https://github.com/kumsumit/vector_graphics_codec.git
  vector_graphics_compiler:
    git: https://github.com/kumsumit/vector_graphics_compiler.git

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - svg
  - vector-graphics
